version: "3.5"
networks:
  wireguard:
services:
  haproxy:
    image: eeacms/haproxy
    ports:
      - "0.0.0.0:1080:1080"
    networks:
      - wireguard
    restart: always
    environment:
      TIMEOUT_CONNECT: 1000
      TIMEOUT_CLIENT: 5000
      TIMEOUT_SERVER: 5000
      FRONTEND_PORT: 1080
      BACKENDS_MODE: tcp
      BACKENDS: "p0:1080 p1:1080 p2:1080 p3:1080 p4:1080 p5:1080 p6:1080 p7:1080 p8:1080 p9:1080 p10:1080 p11:1080 p12:1080 p13:1080 p14:1080 p15:1080 p16:1080 p17:1080 p18:1080 p19:1080 p20:1080 p21:1080 p22:1080 p23:1080 p24:1080 p25:1080 p26:1080 p27:1080 p28:1080 p29:1080 p30:1080 p31:1080 p32:1080 p33:1080 p34:1080 p35:1080 p36:1080 p37:1080 p38:1080 p39:1080 p40:1080 p41:1080 p42:1080 p43:1080 p44:1080 p45:1080 p46:1080 p47:1080 p48:1080 p49:1080 p50:1080 p51:1080 p52:1080 p53:1080 p54:1080 p55:1080 p56:1080 p57:1080 p58:1080 p59:1080 p60:1080 p61:1080 p62:1080 p63:1080 p64:1080 p65:1080 p66:1080 p67:1080 p68:1080 p69:1080 p70:1080 p71:1080 p72:1080 p73:1080 p74:1080 p75:1080 p76:1080 p77:1080 p78:1080 p79:1080 p80:1080 p81:1080 p82:1080 p83:1080 p84:1080 p85:1080 p86:1080 p87:1080 p88:1080 p89:1080 p90:1080 p91:1080 p92:1080 p93:1080 p94:1080 p95:1080 p96:1080 p97:1080 p98:1080 p99:1080"
  p0:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p1:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p2:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p3:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p4:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p5:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p6:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p7:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p8:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p9:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p10:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p11:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p12:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p13:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p14:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p15:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p16:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p17:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p18:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p19:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p20:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p21:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p22:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p23:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p24:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p25:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p26:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p27:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p28:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p29:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p30:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p31:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p32:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p33:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p34:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p35:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p36:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p37:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p38:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p39:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p40:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p41:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p42:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p43:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p44:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p45:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p46:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p47:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p48:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p49:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p50:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p51:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p52:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p53:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p54:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p55:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p56:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p57:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p58:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p59:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p60:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p61:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p62:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p63:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p64:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p65:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p66:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p67:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p68:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p69:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p70:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p71:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p72:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p73:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p74:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p75:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p76:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p77:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p78:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p79:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p80:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p81:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p82:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p83:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p84:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p85:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p86:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p87:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p88:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p89:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p90:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p91:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p92:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p93:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p94:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p95:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p96:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p97:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p98:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
  p99:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    networks:
      - wireguard
