version: "3.5"
networks:
  wireguard:
services:
  haproxy:
    depends_on:
      - p39
    image: eeacms/haproxy
    ports:
      - "0.0.0.0:1080:1080"
    networks:
      - wireguard
    restart: always
    environment:
      LOG_LEVEL: info
      TIMEOUT_CONNECT: 500
      TIMEOUT_CLIENT: 2000
      TIMEOUT_SERVER: 2000
      FRONTEND_PORT: 1080
      BACKENDS_MODE: tcp
      BACKENDS: "p0:1080 p1:1080 p2:1080 p3:1080 p4:1080 p5:1080 p6:1080 p7:1080 p8:1080 p9:1080 p10:1080 p11:1080 p12:1080 p13:1080 p14:1080 p15:1080 p16:1080 p17:1080 p18:1080 p19:1080 p20:1080 p21:1080 p22:1080 p23:1080 p24:1080 p25:1080 p26:1080 p27:1080 p28:1080 p29:1080 p30:1080 p31:1080 p32:1080 p33:1080 p34:1080 p35:1080 p36:1080 p37:1080 p38:1080 p39:1080"
  p0:
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p1:
    depends_on:
      - p0
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p2:
    depends_on:
      - p1
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p3:
    depends_on:
      - p2
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p4:
    depends_on:
      - p3
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p5:
    depends_on:
      - p4
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p6:
    depends_on:
      - p5
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p7:
    depends_on:
      - p6
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p8:
    depends_on:
      - p7
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p9:
    depends_on:
      - p8
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p10:
    depends_on:
       - p9
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p11:
    depends_on:
      - p10
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p12:
    depends_on:
      - p11
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p13:
    depends_on:
      - p12
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p14:
    depends_on:
      - p13
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p15:
    depends_on:
      - p14
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p16:
    depends_on:
      - p15
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p17:
    depends_on:
      - p16
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p18:
    depends_on:
      - p17
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p19:
    depends_on:
      - p18
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p20:
    depends_on:
      - p19
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p21:
    depends_on:
      - p20
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p22:
    depends_on:
      - p21
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p23:
    depends_on:
      - p22
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p24:
    depends_on:
      - p23
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p25:
    depends_on:
      - p24
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p26:
    depends_on:
      - p25
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p27:
    depends_on:
      - p26
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p28:
    depends_on:
      - p27
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p29:
    depends_on:
      - p28
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p30:
    depends_on:
      - p29
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p31:
    depends_on:
      - p30
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p32:
    depends_on:
      - p31
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p33:
    depends_on:
      - p32
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p34:
    depends_on:
      - p33
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p35:
    depends_on:
      - p34
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p36:
    depends_on:
      - p35
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p37:
    depends_on:
      - p36
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p38:
    depends_on:
      - p37
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
  p39:
    depends_on:
      - p38
    image: diwu1989/wireguardproxy
    restart: always
    privileged: true
    environment:
      STAGGERED_START: 30
      RECONNECT_INTERVAL: 90
    networks:
      - wireguard
